name: Swapcore
version: '${version}'
main: bristopher.swapcore.Swapcore
api-version: '1.21.8'
authors: [<Null>, kilololololololobytes]
commands:
  swap:
  
  SwapEdit:
    description: Edit the settings for Swap related variables.
    usage: /SwapEdit <variable> <value>

